version: '3.8'

services:
  mongodb1:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) {rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017',priority:1},{_id:1,host:'host.docker.internal:27018',priority:0.5},{_id:2,host:'host.docker.internal:27019',priority:0.5}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports: 
      - 27017:27017
    volumes:
      - mongodb1_data:/data/db
      - mongodb1_config:/data/configdb
  mongodb2:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018"]  
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    ports: 
      - 27018:27018
    volumes:
      - mongodb2_data:/data/db
      - mongodb2_config:/data/configdb
  mongodb3:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27019"]  
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    ports: 
      - 27019:27019
    volumes:
      - mongodb3_data:/data/db
      - mongodb3_config:/data/configdb

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=stockmarket
      - RABBITMQ_DEFAULT_PASS=supersecret123

  stock-publisher:
    container_name: producer
    image: manuel123456/stock-publisher:latest
    restart: always
    environment:
      - RABBITMQ_URL=amqp://stockmarket:supersecret123@rabbitmq:5672/
      - TICKER_INTERVAL=1
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - stock-liveview1
      - stock-liveview2

  stock-liveview1:
    container_name: stock-liveview1
    image: manuel123456/stock-liveview:latest
    environment:
      - MONGODB_URL=mongodb://mongodb1:27017,mongodb2:27018,mongodb3:27019/?replicaSet=rs0
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 30

  stock-liveview2:
    container_name: stock-liveview2
    image: manuel123456/stock-liveview:latest
    environment:
      - MONGODB_URL=mongodb://mongodb1:27017,mongodb2:27018,mongodb3:27019/?replicaSet=rs0
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 30

  consumer-tesla:
    container_name: stock-consumer-tesla
    image: manuel123456/stock-consumer:latest
    environment:
      - RABBITMQ_URL=amqp://stockmarket:supersecret123@rabbitmq:5672/
      - MONGODB_URL=mongodb://mongodb1:27017,mongodb2:27018,mongodb3:27019/?replicaSet=rs0
      - QUEUE_NAME=TSLA
    depends_on:
      - rabbitmq
      - mongodb1
      - mongodb2
      - mongodb3

  consumer-apple:
    container_name: stock-consumer-apple
    image: manuel123456/stock-consumer:latest
    environment:
      - RABBITMQ_URL=amqp://stockmarket:supersecret123@rabbitmq:5672/
      - MONGODB_URL=mongodb://mongodb1:27017,mongodb2:27018,mongodb3:27019/?replicaSet=rs0
      - QUEUE_NAME=AAPL
    depends_on:
      - rabbitmq
      - mongodb1
      - mongodb2
      - mongodb3

  consumer-microsoft:
    container_name: stock-consumer-microsoft
    image: manuel123456/stock-consumer:latest
    environment:
      - RABBITMQ_URL=amqp://stockmarket:supersecret123@rabbitmq:5672/
      - MONGODB_URL=mongodb://mongodb1:27017,mongodb2:27018,mongodb3:27019/?replicaSet=rs0
      - QUEUE_NAME=MSFT
    depends_on:
      - rabbitmq
      - mongodb1
      - mongodb2
      - mongodb3

volumes:
 mongodb1_data:
 mongodb2_data:
 mongodb3_data:
 mongodb1_config:
 mongodb2_config:
 mongodb3_config: