services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress1
      - wordpress2

  wordpress1:
    image: wordpress:latest
    restart: always
    environment:
      - ...

  wordpress2:
    image: wordpress:latest
    restart: always
    environment:
      - ...